[project]
name = "03-lite-llm-agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nest-asyncio>=1.6.0",
    "openai-agents[litellm]>=0.0.16",
]
